### ISSUE TITLE
CSV with semicolon separated values

### ISSUE THREAD

**Issue by jozeflambrecht** [LaravelDaily/Laravel-Import-CSV-Demo#1]
Hello! I love your import script! How would you make it work that the CSV file could be separated with semicolons or comma's? And is there a reason why you use Excel or str_getcsv or is this just to show there are 2 options?

```
        if ($request->has('header')) {
            $data = Excel::load($path, function($reader) {})->get()->toArray();
        } else {
            $data = array_map('str_getcsv', file($path));
        }
```

Thanks!

**Comment by PovilasKorop** [comment]
@jozeflambrecht thanks for the question, it was just easier to integrate that Excel package for the case that there was a header line, but it's not necessary.

You can choose delimiter in str_getcsv documentation,  here: http://php.net/manual/en/function.str-getcsv.php
